pipeline {
    agent any 
    tools { terraform 'Terraform' }
    stages {
        stage('Terraform') {
            steps {
                sh 'terraform init'
                sh 'terraform apply '
            }
        }
        
    }
}